import { FieldConfig, SectionMeta, FormData } from './types';

export const SECTIONS: SectionMeta[] = [
  { id: 'personal', title: '个人信息', description: '基本身份与联系方式' },
  { id: 'professional', title: '专业背景', description: '教育、工作经历与技能' },
  { id: 'preferences', title: '职业偏好', description: '期望职位、行业与目标' },
  { id: 'financial_legal', title: '财务与合规', description: '薪资期望、法律声明与敏感信息' },
  { id: 'meta', title: '元数据与授权', description: '文件附件与数据授权' },
];

// Mapped from the provided CSV content
export const FIELDS: FieldConfig[] = [
  // --- Personal ---
  { key: 'first_name', label: '您的名字（名）', category: 'personal', isSensitive: false, isOptional: false },
  { key: 'last_name', label: '您的姓氏', category: 'personal', isSensitive: false, isOptional: false },
  { key: 'nickname', label: '常用称呼/昵称', category: 'personal', isSensitive: false, isOptional: true },
  { key: 'birth_date', label: '出生日期', category: 'personal', isSensitive: true, isOptional: false, type: 'date' },
  { key: 'gender', label: '性别', category: 'personal', isSensitive: false, isOptional: true, type: 'select', options: ['男', '女', '其他', '不愿透露'] },
  { key: 'city', label: '当前所在城市', category: 'personal', isSensitive: false, isOptional: false },
  { key: 'country', label: '当前所在国家', category: 'personal', isSensitive: false, isOptional: false },
  { key: 'timezone', label: '您的时区', category: 'personal', isSensitive: false, isOptional: false },
  { key: 'email', label: '主要联系邮箱', category: 'personal', isSensitive: true, isOptional: false, type: 'email' },
  { key: 'phone', label: '手机号（含区号）', category: 'personal', isSensitive: true, isOptional: false, type: 'tel' },
  { key: 'alt_contact', label: '备用联系方式（微信/LinkedIn 等）', category: 'personal', isSensitive: false, isOptional: true },
  { key: 'family_responsibilities', label: '家庭照护责任', category: 'personal', isSensitive: true, isOptional: true, type: 'textarea' },
  { key: 'living_stability', label: '是否计划搬家/迁移', category: 'personal', isSensitive: false, isOptional: false },

  // --- Professional ---
  { key: 'education_highest', label: '最高学历（学位+专业+学校）', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'education_year', label: '毕业年份', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'education_other', label: '其他教育经历', category: 'professional', isSensitive: false, isOptional: true, type: 'textarea' },
  { key: 'certifications', label: '证书（名称+机构+编号+到期）', category: 'professional', isSensitive: false, isOptional: true, type: 'textarea' },
  { key: 'current_company', label: '当前公司名称', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'current_department', label: '当前部门', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'current_title', label: '当前职位名称', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'current_role_start', label: '当前职位开始时间', category: 'professional', isSensitive: false, isOptional: false, type: 'date' }, // Simplified date input
  { key: 'current_location', label: '当前工作地点', category: 'professional', isSensitive: false, isOptional: false, type: 'select', options: ['远程', '现场', '混合'] },
  { key: 'employment_type', label: '工作类型', category: 'professional', isSensitive: false, isOptional: false, type: 'select', options: ['全职', '兼职', '合同', '顾问'] },
  { key: 'reporting_line', label: '您的直属汇报对象职位', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'past_experience', label: '过往工作经历（公司+职位+年月+职责）', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'key_achievements', label: '3-10 项可量化成果', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'portfolio_links', label: '作品集/GitHub/案例链接', category: 'professional', isSensitive: false, isOptional: true },
  { key: 'professional_publications', label: '发表文章/专利/演讲等', category: 'professional', isSensitive: false, isOptional: true, type: 'textarea' },
  { key: 'skills', label: '主要技能列表', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea', placeholder: '逗号分隔' },
  { key: 'skill_levels', label: '技能熟练度', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea', placeholder: '初/中/高/专家 或 1-10' },
  { key: 'languages', label: '语言能力（含等级）', category: 'professional', isSensitive: false, isOptional: false },
  { key: 'technical_stack', label: '技术栈（含使用年限）', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'soft_skills', label: '软技能（沟通/协作/领导等）', category: 'professional', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'leadership_experience', label: '管理经验（团队规模/职责）', category: 'professional', isSensitive: false, isOptional: true, type: 'textarea' },

  // --- Preferences ---
  { key: 'relocation_open', label: '是否接受搬迁（是/否/条件）', category: 'preferences', isSensitive: false, isOptional: false },
  { key: 'travel_readiness', label: '可接受的出差比例（%）', category: 'preferences', isSensitive: false, isOptional: false, type: 'number' },
  { key: 'short_term_goals', label: '短期职业目标（6-12 个月）', category: 'preferences', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'long_term_goals', label: '长期职业目标（1-3 年+）', category: 'preferences', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'preferred_roles', label: '期望职位', category: 'preferences', isSensitive: false, isOptional: false },
  { key: 'preferred_industries', label: '期望行业', category: 'preferences', isSensitive: false, isOptional: false },
  { key: 'preferred_company_size', label: '公司规模偏好', category: 'preferences', isSensitive: false, isOptional: false },
  { key: 'preferred_culture', label: '公司文化偏好', category: 'preferences', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'work_mode_preference', label: '工作模式偏好', category: 'preferences', isSensitive: false, isOptional: false, type: 'select', options: ['远程', '混合', '现场'] },
  { key: 'commute_tolerance', label: '可接受的通勤时间（分钟）', category: 'preferences', isSensitive: false, isOptional: false, type: 'number' },
  { key: 'personality_test', label: '人格测评结果 (Big Five/MBTI)', category: 'preferences', isSensitive: false, isOptional: true },
  { key: 'interest_test', label: '职业兴趣测评 (RIASEC)', category: 'preferences', isSensitive: false, isOptional: true },
  { key: 'cognitive_test', label: '能力/逻辑/情境测试结果', category: 'preferences', isSensitive: false, isOptional: true },
  
  // --- Financial & Legal ---
  { key: 'work_authorization', label: '工作许可/签证状态及到期时间', category: 'financial_legal', isSensitive: true, isOptional: false },
  { key: 'health_limitations', label: '是否有影响工作的健康状况', category: 'financial_legal', isSensitive: true, isOptional: true, type: 'textarea' },
  { key: 'work_adjustments', label: '是否需要工作场所调整', category: 'financial_legal', isSensitive: true, isOptional: true, type: 'textarea' },
  { key: 'salary_current', label: '当前薪资（总包+细项）', category: 'financial_legal', isSensitive: true, isOptional: false, type: 'textarea' },
  { key: 'salary_expectation_low', label: '期望最低薪资', category: 'financial_legal', isSensitive: true, isOptional: false, type: 'number' },
  { key: 'salary_expectation_high', label: '期望最高薪资', category: 'financial_legal', isSensitive: true, isOptional: false, type: 'number' },
  { key: 'comp_structure_preference', label: '薪酬结构偏好（固定/奖金/股票）', category: 'financial_legal', isSensitive: true, isOptional: false },
  { key: 'financial_buffer', label: '财务缓冲（可维持月数）', category: 'financial_legal', isSensitive: true, isOptional: true, type: 'number' },
  { key: 'liabilities', label: '主要负债情况', category: 'financial_legal', isSensitive: true, isOptional: true, type: 'textarea' },
  { key: 'legal_noncompete', label: '是否有竞业协议？内容要点？', category: 'financial_legal', isSensitive: true, isOptional: false, type: 'textarea' },
  { key: 'legal_confidentiality', label: '保密义务（是否存在及主要条款）', category: 'financial_legal', isSensitive: true, isOptional: false, type: 'textarea' },
  { key: 'stock_vesting', label: '未归属股权/限制性条件', category: 'financial_legal', isSensitive: true, isOptional: false },
  
  // --- Meta / Recruitment ---
  { key: 'open_to_new_roles', label: '当前求职活跃度', category: 'meta', isSensitive: false, isOptional: false },
  { key: 'application_channels', label: '使用的求职渠道', category: 'meta', isSensitive: false, isOptional: false },
  { key: 'interview_history', label: '过去 6 个月的面试情况', category: 'meta', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'rejection_reasons', label: '被拒原因/反馈', category: 'meta', isSensitive: false, isOptional: true, type: 'textarea' },
  { key: 'resume_file_id', label: '简历文件上传 ID', category: 'meta', isSensitive: false, isOptional: true },
  { key: 'work_samples_files', label: '其他作品或附件 ID', category: 'meta', isSensitive: false, isOptional: true },
  { key: 'availability_date', label: '最早可到岗日期', category: 'meta', isSensitive: false, isOptional: false, type: 'date' },
  { key: 'notice_period', label: '离职需提前通知期', category: 'meta', isSensitive: false, isOptional: false },
  { key: 'data_source', label: '信息来源', category: 'meta', isSensitive: false, isOptional: false },
  { key: 'consent_scope', label: '信息授权范围', category: 'meta', isSensitive: false, isOptional: false, type: 'textarea' },
  { key: 'consent_timestamp', label: '同意分享数据的时间', category: 'meta', isSensitive: false, isOptional: false, type: 'date' },
];

export const EXAMPLE_DATA: FormData = {
  // Personal
  first_name: 'Alex',
  last_name: 'Chen',
  nickname: 'AC',
  birth_date: '1995-05-15',
  gender: '男',
  city: '深圳',
  country: '中国',
  timezone: 'GMT+8',
  email: 'alex.chen.demo@example.com',
  phone: '13800138000',
  alt_contact: 'WeChat: alexcpp_dev',
  family_responsibilities: '目前无特殊照护责任',
  living_stability: '稳定，未来2年无跨城市搬家计划',
  
  // Professional
  education_highest: '硕士，通信与信息系统，电子科技大学',
  education_year: '2020',
  education_other: '本科，通信工程，西安电子科技大学 (2013-2017)',
  certifications: 'CET-6 (620), 软考高级-系统架构设计师',
  current_company: 'FutureNetwork Tech',
  current_department: '核心网研发部',
  current_title: '高级 C++ 软件工程师',
  current_role_start: '2020-07-01',
  current_location: '现场',
  employment_type: '全职',
  reporting_line: '研发总监',
  past_experience: '2019-2020: 实习生 @ 某通信大厂，负责协议栈模块单元测试与维护。\n2017-2019: 研究生实验室项目，负责 5G 接入网仿真平台搭建。',
  key_achievements: '1. 优化了核心网网关数据转发模块，通过引入无锁队列和内存池技术，将吞吐量提升了 35%。\n2. 主导了遗留代码重构项目，将原有 C++98 代码库升级至 C++17 标准，减少了 20% 的代码行数并提升了可维护性。\n3. 排查并解决了一个导致线上服务偶发崩溃的竞态条件问题。',
  portfolio_links: 'github.com/alexchen-demo',
  professional_publications: '《基于 SDN 的 5G 网络切片资源调度算法研究》，发表于《通信学报》',
  skills: 'C++, Linux System Programming, Network Programming (TCP/IP), Multithreading, Docker, Kubernetes, Python',
  skill_levels: 'C++: 精通, Linux: 熟练, Python: 熟悉',
  languages: '中文 (母语), 英语 (工作流利，可作为工作语言)',
  technical_stack: 'C++17, STL, Boost, gdb, CMake, Protobuf, gRPC, Jenkins',
  soft_skills: '问题解决能力强，乐于分享技术，良好的跨团队沟通能力',
  leadership_experience: '曾指导 2 名校招新员工完成入职培训和试用期考核',

  // Preferences
  relocation_open: '是，如果薪资涨幅超过 30% 且地点在一线城市',
  travel_readiness: '15',
  short_term_goals: '深入理解分布式存储系统，成为团队内的技术骨干。',
  long_term_goals: '成为一名系统架构师，负责大规模高并发系统的设计。',
  preferred_roles: '资深 C++ 研发工程师，系统开发工程师',
  preferred_industries: '云计算，高性能计算，量化交易',
  preferred_company_size: '500人以上',
  preferred_culture: '工程师文化浓厚，技术驱动，信息透明',
  work_mode_preference: '混合',
  commute_tolerance: '45',
  personality_test: 'INTJ-A',
  interest_test: 'Investigative (研究型)',
  cognitive_test: '逻辑推理能力前 10%',

  // Financial & Legal
  work_authorization: '中国国籍，无签证限制',
  health_limitations: '无',
  work_adjustments: '无',
  salary_current: '月薪 35k * 15薪 + 股票期权',
  salary_expectation_low: '600000',
  salary_expectation_high: '800000',
  comp_structure_preference: '偏好高现金部分 (High Base)',
  financial_buffer: '6',
  liabilities: '房贷月供 12k',
  legal_noncompete: '有竞业协议，范围主要涉及通信设备竞对，有效期 1 年',
  legal_confidentiality: '签署了标准保密协议',
  stock_vesting: '尚有 20% 股票未归属，预计明年 7 月归属',

  // Meta
  open_to_new_roles: '开放机会 (Open to work)',
  application_channels: '猎头，内推',
  interview_history: '上个月面试了 2 家量化私募，均进入终面',
  rejection_reasons: '其中一家因为策略方向不匹配未发 offer',
  resume_file_id: 'resume_alex_chen_v2.pdf',
  work_samples_files: 'demo_code_sample.zip',
  availability_date: '2024-03-01',
  notice_period: '1 个月',
  data_source: '本人填写',
  consent_scope: '同意用于招聘流程中的评估与背调',
  consent_timestamp: '2024-01-20'
};
